### ISSUE TITLE
[Bug]: `Error detected while processing VimEnter Autocommands for "*":`

### ISSUE THREAD

**Issue by bennypowers** [mrjones2014/legendary.nvim#116]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.7.0-dev+1437-g356cff78e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by bennyp@iMac

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-356cff7/share/nvim"

Run :checkhealth for more info

### Expected Behavior

as per README

### Actual Behavior

I can launch the command palette, but which-key no longer displays prompts for registered bindings

### Minimal Configuration to Reproduce

working on it... TBD

### Additional Details and/or Screenshots

Error when launching nvim:
```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua .../start/legendary.nvim/lua/legendary/compat/which-key.lua:31: attempt to get length of a boolean value
stack traceback:
        .../start/legendary.nvim/lua/legendary/compat/which-key.lua:31: in function <.../start/legendary.nvim/lua/legendary/compat/which-key.lua:27
>
        vim/shared.lua: in function 'tbl_map'
        .../start/legendary.nvim/lua/legendary/compat/which-key.lua:27: in function 'parse_whichkey'
        .../start/legendary.nvim/lua/legendary/compat/which-key.lua:46: in function 'bind_whichkey'
        .../start/legendary.nvim/lua/legendary/compat/which-key.lua:56: in function 'register'
        ...rt/which-key.nvim/lua/which-key/plugins/presets/misc.lua:86: in function 'setup'
        ...rt/which-key.nvim/lua/which-key/plugins/presets/init.lua:86: in function 'setup'
        ...cker/start/which-key.nvim/lua/which-key/plugins/init.lua:37: in function '_setup'
        ...cker/start/which-key.nvim/lua/which-key/plugins/init.lua:19: in function 'setup'
        .../pack/packer/start/which-key.nvim/lua/which-key/init.lua:87: in function 'load'
        [string ":lua"]:1: in main chunk
        ```

**Comment by bennypowers** [comment]
It's likely that some changes to master in https://github.com/neovim/neovim/issues/14090 are underlying this issue

**Comment by mrjones2014** [comment]
Looks like it was a bug with the which-key integration, I think something changed there. @bennypowers  can you test #117
