### ISSUE TITLE
Check here for breaking changes

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#119]
Neovim changed `nvim_add_user_command` to `nvim_create_user_command`, update to latest Neovim if you run into an error relating to this.

**Comment by mrjones2014** [comment]
`auto_load_whichkey` was changed to false by default.

**Comment by danielo515** [comment]
So you made force push and removed commits from the history? I was depending on 5930919, which commit should I use now in order to keep using the old API?

**Comment by mrjones2014** [comment]
You should be able to use the v1.0.0 tag: https://github.com/mrjones2014/legendary.nvim/releases/tag/v1.0.0

**Comment by mrjones2014** [comment]
Closing as we now support semantic versioning.

**Comment by tjkirch** [comment]
> Closing as we now support semantic versioning.

This thread would still be very useful to keep open for notifications of breaking changes specifically.

**Comment by mrjones2014** [comment]
You can read the release notes on each release here: https://github.com/mrjones2014/legendary.nvim/releases

Hard breaking changes will mean a major release going forward, and I think pretty much all plugin managers support pinning to a commit or tag. Is something about this not sufficient?
