### ISSUE TITLE
[Bug]: Legendary thinks all `which-key` mappings are in normal mode

### ISSUE THREAD

**Issue by lmburns** [mrjones2014/legendary.nvim#127]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```
NVIM v0.7.0-dev+1443-gdbd5242d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-353

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Expected Behavior

I would expect for a mapping created in `which-key`, which has a mode other than `n`, would be picked up by `legendary` as that same mode.

### Actual Behavior

`legendary` thinks that all `which-key` bindings are in normal mode.

### Minimal Configuration to Reproduce

An example of a `which-key` binding that is not in normal mode is the following example.

```lua
require('which-key").register(
    {
        ["d"] = {[["_d]], "Delete (blackhole)"},
    },
    {mode = "v"}
)
```

When looking in `legendary` I see the following line:

```
n       │ d                       │ Delete (blackhole)   
```

Whenever creating a binding with `legendary` that species a mode, like the following example, everything is fine.

```lua
require("legendary").bind_keymap(
    {
        "<C-,>",
        "<Cmd>Legendary keymaps<CR>",
        description = "Show Legendary keymaps",
        mode = {"n", "i", "x"}
    }
)
```

When looking in `legendary` I see the following line:

```
n, i, x │ <C-,>                   │ Show Legendary keymaps  
```

**Comment by mrjones2014** [comment]
Should be fixed, reopen otherwise.

**Comment by mcwhitfield** [comment]
This appears to have regressed -- keymaps without an implementation hit [this path](https://github.com/mrjones2014/legendary.nvim/blob/master/lua/legendary/data/keymap.lua#L69)  and end up with an empty `mode_mapping`, then end up with the [default](https://github.com/mrjones2014/legendary.nvim/blob/master/lua/legendary/data/keymap.lua#L123) value in the [formatter](https://github.com/mrjones2014/legendary.nvim/blob/master/lua/legendary/ui/format.lua#L20).

**Comment by mrjones2014** [comment]
I think this is the same issue as #271, so I'll close this as a duplicate.
