### ISSUE TITLE
[Feature]: Option to only show mappings of the current mode

### ISSUE THREAD

**Issue by lmburns** [mrjones2014/legendary.nvim#129]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

[`fzf.vim`](https://github.com/junegunn/fzf.vim) provides four different mappings, which only show the mappings in the mode that the user is in.

Here they are in `fzf.vim`'s plugin.

https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L147-L150

I'm proposing an option that would allow for the user to do the same with `legendary`, as opposed to listing all mappings that are currently listed. Perhaps one could do that as well.

I've searched through the documentation of legendary and haven't seen anything about this. If I've somehow missed this, I am sorry.

**Comment by mrjones2014** [comment]
Does #131 work for you? Can you test it out?

**Comment by lmburns** [comment]
Yes it does work, the mappings that are displayed are correct.

I tried `n`, `i`, and `v` mappings to make sure they all worked and they do, the only thing is that it also displays commands.

I tried the following commands:

```lua
require("legendary").find(nil, require("legendary.filters").mode("n"))
require("legendary").find("keymaps", require("legendary.filters").mode("n"))
```

Am I doing something wrong to only display the mappings?

**Comment by mrjones2014** [comment]
Hmm, the following should show only key mappings: 
```lua
require("legendary").find("keymaps", require("legendary.filters").mode("n"))
```

that’s showing commands for you? If so I probably broke that functionality by accident in that PR.

**Comment by lmburns** [comment]
Yeah it does. Also, even before this pull request, the settings `include_builtin` and `include_legendary` always show the builtin and `:Legendary` commands, regardless of whether or not their value is `true` or `false`.
![rec](https://user-images.githubusercontent.com/44355502/163737662-01e7da46-e23a-4db8-9d41-edee60ae16f7.gif)

**Comment by lmburns** [comment]
The commands are still shown when listing mappings using that function, but I did realize something odd that fixed the `include_builtin` and `include_legendary_cmds`.

I have my Neovim configuration setup where I my `lua` folder structured like:
```
- plugs/ (directory of plugin files)
- mappings.lua
- plugins.lua
- etc.
```

The `legendary` file is in the `plugs` directory. When setting options from within that file, all seem to work except for the two mentioned above (i.e., `include_builtin`, `include_legendary_cmds`). 

In the `mappings.lua` file, I have mappings that aren't specific to any plugin. I use `which-key` in that file to register most of the bindings. `legendary` doesn't pick them up for some reason (`which-key` does). I thought maybe that since it is in folder that is one level higher than the original `legendary.setup()` call, it isn't being picked up. That does seem to be the reason why they aren't being registered with `legendary`. So, I tried making another call to `legendary.setup()` from within the `mappings.lua` file, and now they seem to be registered.

The reason for explaining all of this is to say that `include_builtin` and `include_legendary_cmds` do not work whenever they are set from within the `lua/plugs/legendary.lua` file, but do work whenever they are set in the `lua/mappings.lua` file. 

So, my comment about those two options not working can be disregarded. Commands are still shown when listing keymaps though

**Comment by mrjones2014** [comment]
I’ve been unable to reproduce the issue you’re having with `include_builtin` and `include_legendary_cmds` not taking effect. If it’s still an issue, can you open a separate issue with a minimal reproducible init.lua?

As far as the which-key integration though, it sounds like you could be running into this issue: https://github.com/mrjones2014/legendary.nvim/issues/78

Basically, `which-key.nvim` needs to be available on the runtime path when you call `require(‘legendary’).setup()` in order for the which-key listener to be set up properly.

**Comment by mrjones2014** [comment]
I just tested out the PR and I’m also unable to reproduce commands showing no matter what.

Can you post a minimal reproducible init.lua? Use the template here: https://github.com/mrjones2014/legendary.nvim/discussions/93

**Comment by mrjones2014** [comment]
I'm going to merge the PR linked to this issue, because the filtering feature itself is working.

The other issues you've mentioned in this thread I've been unable to reproduce. If you're still having issues, feel free to file a separate bug issue, and make sure to include a minimal reproducible init.lua based on the template.
