### ISSUE TITLE
[Feature]: Allow to add all user commands

### ISSUE THREAD

**Issue by gkzhb** [mrjones2014/legendary.nvim#141]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Now users have to manually register commands(from other plugins) for `legendary.nvim`. It's not convenient to use this plugin as command fuzzy finder and trigger commands.

I believe we can provide a setup option to allow users to add all the user commands to `legendary.nvim` with lua API `vim.api.nvim_get_commands` just like telescope `builtin.commands`.

**Comment by mrjones2014** [comment]
Duplicate of #39
