### ISSUE TITLE
[Feature]: allow anonymous commands

### ISSUE THREAD

**Issue by metalelf0** [mrjones2014/legendary.nvim#142]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Maybe this is something that is not a legendary.nvim responsibility, or it can be done in other ways.

I want to be able to add shorthands for long commands, without either having to set a keymap or a command for them.

E.g., let's say I want to open the `legendary.nvim` popup, type `cap` and have it run `:Neorg gtd capture`.

Right now I see two solutions:
- map it to a custom command (e.g. `:LegendaryCommandNeorgGtdCapture`);
- map it to a keymap (e.g. `<Leader>ngc`).

Both have disadvantages in polluting the command namespace and creating useless bindings. 

A possible implementation would be that 

```lua
local commands = {
  -- ...
  {  nil, ':Neorg gtd capture', description = 'Neorg gtd: capture task' },
}
```

would create a custom command (e.g. `LegendaryCommand001`), and command names starting with `LegendaryCommand` would be hidden in the legendary popup to avoid cluttering the interface.

What do you think?

**Comment by mrjones2014** [comment]
Couldn't you just do

```lua
local commands = {
  {  ':Neorg gtd capture', description = 'Neorg gtd: capture task' },
}
```

This will add the command to the finder without binding it to an implementation (since it only has one list element).

**Comment by metalelf0** [comment]
Oh, yes. That's exactly what I needed. I didn't try it cause I didn't see it in the documentation. Thanks!

**Comment by mrjones2014** [comment]
Will note that in #106, thanks
