### ISSUE TITLE
[Feature]: Some of my personal opinions

### ISSUE THREAD

**Issue by yyy33** [mrjones2014/legendary.nvim#160]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

1. Let `legendary.find()` function support `select_prompt` option
2. The select_prompt option returns the number of relevant entries, like 'map(25)/command(37)/autocmd(44)'
3. Cancel the kind option of the find function, which can already be done by the filter option
4. Set the content of the first column as a beautiful icon, rather than 'n' or '<cmd>' and other text, so that the content space can also be more concise
5. Add tags to each command or mapping, then you can filter by tag in ui-select,

**Comment by mrjones2014** [comment]
>Add tags to each command or mapping, then you can filter by tag in ui-select,

Actually, you can do this yourself with the current API.

Just add a `tags = { 'some tag', 'some other tag' }` on each item, then use a custom format function.

**Comment by mrjones2014** [comment]
>The select_prompt option returns the number of relevant entries, like 'map(25)/command(37)/autocmd(44)'

This would dynamically update while searching, and there isn't any way to do this. Unless I'm misunderstanding what you mean.

**Comment by mrjones2014** [comment]
>Cancel the kind option of the find function, which can already be done by the filter option

Not only is this a breaking change, it's also used to compute the prompt title, so we can't really do this.

I will make `select_prompt` an option you can pass to find though.
