### ISSUE TITLE
[Feature]: Auto execute commands

### ISSUE THREAD

**Issue by danielo515** [mrjones2014/legendary.nvim#195]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Right now, when I select a command in the finder, I have to hit enter once more to execute it. I will love an option to just automatically execute the command when it gets selected.

**Comment by mrjones2014** [comment]
You shouldn't have to press enter again to execute it. How's your command set up?

Also check if it works on v2, see #191, commands are executed via `vim.cmd` instead of `nvim_feedkeys` on that branch.

**Comment by danielo515** [comment]
create_sibling_file is a lua function:

```lua
local bind_command = require("legendary").bind_command  
bind_command {
    ":CreateSibling",
    create_sibling_file,
    description = "Create a new file that is a sibling of the current one",
  }
```

**Comment by mrjones2014** [comment]
I can't reproduce on either v1 or v2.

Please provide a minimally reproducible configuration based on this: https://github.com/mrjones2014/legendary.nvim/discussions/93

**Comment by mrjones2014** [comment]
Closing because stale. Let me know if you can reproduce with an example config and I'll reopen.

**Comment by danielo515** [comment]
I tried to reproduce it here:
https://gist.github.com/danielo515/48c39ce6aaba70a2516791078a278336

But packer fails to install your plugin for some reason

**Comment by gouez** [comment]
I'm having the same issue too

![cc](https://user-images.githubusercontent.com/4373882/203692796-27b9a80f-a276-4158-aafe-6c98c4e0ba63.gif)

**Comment by danielo515** [comment]
Just to clarify, this does not happen in the latest version, so it is probably not worth investigtating
