### ISSUE TITLE
[Feature]: per-mode implementations for commands

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#215]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I have a command defined like this in my config:

```lua
{
  ':Comment',
  function()
    local keys = 'gcc'
    if require('legendary.toolbox').is_visual_mode() then
      keys = 'gc'
    end

    vim.api.nvim_feedkeys(keys, 't', true)
  end,
  description = 'Toggle comment',
}
```

What I'd like to be able to do is a similar syntax to keymaps:

```lua
{
  ':Comment',
  {
    n = 'gc',
    v = 'gcc',
  },
  description = 'Toggle comment',
}
```

**Comment by hinell** [comment]
@mrjones2014 Can we have the same feature, but for `legendary.funcs(...)`? There functions, that can only be run in visual mode, so it's logical to have `{ mode = {...} }` restrictions. 

Should I fill a separate bug request?
