### ISSUE TITLE
[Feature]: Feedback needed: Should legendary.nvim implement a custom telescope.nvim picker with extra features not possible to do with `vim.ui.select()`?

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#236]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

>Shortcuts - Sometimes I have a list of results and the one I want is a few results below. It would be cool to hit a shortcut e.g. <Ctrl-5> to access that result

-- @olimorris

This would be do-able only if we create a custom telescope.nvim picker instead of using `vim.ui.select()`. If there is enough community demand for this, I'll definitely consider working on it.

I would also take a PR if someone wants to work on this.

**Comment by olimorris** [comment]
I'm biased with this issue but I also very much prefer the ui of Telescope to `vim.ui.select()`.

With `vim.ui.select()` the input row is too small imo; I'd prefer some extra padding:

![Screen Shot 2022-12-06 at 08 33 33@2x](https://user-images.githubusercontent.com/9512444/205860856-e722ba6a-452f-4feb-bb70-e4987549a0aa.png)

Plus with Telescope you have the rich coloured icons and you can make it fit into your overall Neovim aesthetic:

<img width="1342" alt="Screen Shot 2022-12-06 at 08 34 42@2x" src="https://user-images.githubusercontent.com/9512444/205861040-317586a8-6b19-4644-89e2-4c4fd5968024.png">

Plus I think the ability to add custom actions could open the door to some very interesting possibilities. The shortcut one listed above for example...or the possibility of stacking actions. I could press `<tab>` on a keymap/command in `legendary.nvim`, to select it, then pressing `<C-CR>` could trigger them to run sequentially (assuming they all had the same mode defined). I'm brainstorming here (😆) but think Telescope opens up a world of really interesting possibilities.

**Comment by mrjones2014** [comment]
>I'm biased with this issue but I also very much prefer the ui of Telescope to vim.ui.select().
>
>With vim.ui.select() the input row is too small imo; I'd prefer some extra padding

With dressing.nvim you can pass whatever telescope configuration you want to `vim.ui.select()` via dressing.nvim's config.

>The shortcut one listed above for example

I do really like that one, I'd probably use that myself.

> I could press <tab> on a keymap/command in legendary.nvim, to select it, then pressing <C-CR> could trigger them to run sequentially (assuming they all had the same mode defined)

That's a neat idea 🤔

**Comment by mrjones2014** [comment]
I've got some down time so I'm gonna put some work into this.

**Comment by mrjones2014** [comment]
Wait a minute. I just had a thought. @olimorris couldn't you just pass custom telescope.nvim config the same way we're now recommending you do it for frecency sorting?

From the README.md:


```lua
  -- Options for list sorting. Note that fuzzy-finders will still
  -- do their own sorting. For telescope.nvim, you can set it to use
  -- `require('telescope.sorters').fuzzy_with_index_bias({})` when
  -- triggered via `legendary.nvim`. Example config for `dressing.nvim`:
  --
  -- require('dressing').setup({
  --  select = {
  --    get_config = function(opts)
  --      if opts.kind == 'legendary.nvim' then
  --        return {
  --          telescope = {
  --            sorter = require('telescope.sorters').fuzzy_with_index_bias({})
  --          }
  --        }
  --      else
  --        return {}
  --      end
  --    end
  --  }
  -- })
```

**Comment by mrjones2014** [comment]
Hmm, I guess there are actually still some things that you couldn't do with the interface of `vim.ui.select()` at all, such as the ability to use telescope.nvim to select multiple items with tab, then run them sequentially on confirm.

**Comment by olimorris** [comment]
Yeah I think Telescope gives you that ability to do complex actions like we've mentioned above. I'm in two minds about this as a feature if it's going to add a tonne of complexity.

**Comment by mrjones2014** [comment]
It won't be that much complexity. The approach I'm taking is to basically have multiple UI "providers" where the default one is `vim.ui.select()`, unless telescope is installed then it defaults to telescope, but all providers must provide the same interface as `vim.ui.select()`. You can bolt additional features like keymaps etc. and eventually I will update it to support multi-select, but it must accept the same options and configuration as `vim.ui.select()`. That makes the internal implementation a lot easier.
