### ISSUE TITLE
[Feature]: More ways to filter items, e.g. by filetype

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#256]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

There are some really great plugins out there which bind their own keymaps that only apply in buffers managed by the plugin. A great example is `octo.nvim` which sets keymaps on buffers with the `octo` buffer type.

Another great example is `glance.nvim` which I just discovered.

We need a way to add these keymaps to `legendary.nvim` but have them only apply when they're actually applied.

I'm thinking an API like:

```lua
-- example octo.nvim keymapping
{
  '<leader>io',
  description = 'Reopen issue',
  filter = {
    buftype = 'octo',
  },
},
```

I'm thinking the following filters should be available:

- `buftype`
- `filetype`
- `custom` which is a function you can write yourself like `custom = function(context) end` where `context` is the same context that our internal keymap executor receives

Would love input from users, cc: @olimorris

**Comment by mrjones2014** [comment]
I'm hesitant to add a `custom` one because if a user writes a `custom` filter that isn't `:h api-fast` that could cause issues, but there isn't really a way to enforce that, and it would be difficult for users to diagnose the issue without just asking me about it.

**Comment by olimorris** [comment]
I think this is a great idea! I personally love the idea of having duplicate keymaps. Like for example `<Leader>f` which could mean two different things based on `buftype`

**Comment by mrjones2014** [comment]
So _setting_ keymaps like that will be a little more complicated, and I didn't think about this use case, but we may be able to do that too.

I was more so thinking about plugin keymappings, like the keymappings that are set on the views for `octo.nvim` or `DiffView.nvim` -- keymaps that are set by the plugin on specific buffers.

However maybe there's a way to _create_ keymaps like this as well, like you described. Internally, in addition to improving the filtering logic, we'd basically need to transparently set up an autocmd so that the keymap is applied on `BufEnter` of the specific file/buftype you've selected.

We'd then need to update filtering to take that into account -- for example, if you have a 'default' mapping for `<leader>f`, and a `buftype` mapping for the same key, only the `buftype` one should appear if you trigger the finder from that buftype.

Actually this same logic should be applied to `opts.buffer` but currently is not.
