### ISSUE TITLE
[Feature]: Classify built-in commands

### ISSUE THREAD

**Issue by hinell** [mrjones2014/legendary.nvim#262]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I propose to classify (add prefix) to built in commands. descriptions so it's easier to navigate:

```
Navigation: go to ...
Tabs: go to the last ...
Window: vertically split
Motion: ...
etc
```

**Comment by hinell** [comment]
Well item groups won't be as conveniet as simple list.... but let's see.

**Comment by mrjones2014** [comment]
Closing as duplicate of #306

**Comment by hinell** [comment]
@mrjones2014 Sorry, but these are different. When I mean classify, I mean "append a name to the specific groups of functionality". E.g.:

```
Tabs: previous tab
Tabs: next tab
Tabs: close
Buffer: change a line
...

```

**Comment by mrjones2014** [comment]
To me that's the exact purpose of item groups

**Comment by hinell** [comment]
@mrjones2014 Item groups would be iconveniet to search across.
