### ISSUE TITLE
[Bug]: Autocommands with a description are created twice 

### ISSUE THREAD

**Issue by mcwhitfield** [mrjones2014/legendary.nvim#270]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```
NVIM v0.9.0-dev-519+g2d8bbe468
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Expected Behavior

Calling `legendary.setup` with arguments following the structure in the [table structure doc](https://github.com/mrjones2014/legendary.nvim/blob/master/doc/table_structures/AUTOCMDS.md#augroups-and-autocmds)  with a non-nil `descripton` results in a single copy of each supplied autocommand.

### Actual Behavior

Each autocommand in the group is created twice, and executed twice on the corresponding event.

### Minimal Configuration to Reproduce

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
vim.g.loaded_remote_plugins = ""
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'mrjones2014/legendary.nvim',
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('legendary').setup { autocmds = {{
    "User",
    function() print("test") end,
    description = "foo",
  }}}
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing legendary.nvim and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config(); vim.api.nvim_exec_autocmds('User', {}) ]]
-- "test" printed twice to :messages
```

### Output from :LegendaryLog

<details>
<summary><code>:LegendaryLog</code> output (click to expand)</summary>

```
[Tue 20 Dec 2022 08:31:53 PM EST][legendary.nvim] setup() parsed and applied all configuration.
```
</details>

**Comment by mrjones2014** [comment]
There is actually a bug, but your minimal config is incorrect so you would see this behavior regardless of the bug, I think. The `User` autocmd must always have `opts.pattern`, where `pattern` is the user-defined name, such as `User PackerComplete`, in this example the `opts.pattern` is `PackerComplete`.

Since you have an autocmd set up for the `User` autocmd without a pattern, you're getting it printed twice because once is from the `User PackerComplete` autocmd and one is from your `vim.api.nvim_exec_autocmds('User', {})` line.

However it does appear the item is getting created twice.
