### ISSUE TITLE
[Feature]: Custom parser API

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#276]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Currently legendary supports a somewhat opinionated DSL for keymaps, commands, etc.

It would be cool, as a user, to be able to do something like:

```lua
require(‘legenday’).setup({
  keymaps = { --[[ keymaps here, but with a custom DSL ]] },
  commands = { --[[ commands here, but with a custom DSL ]] },
  autocmds = { --[[ autocmds here, but with a custom DSL ]] },
  funcs = { --[[ functions here, but with a custom DSL ]] },
  parsers =  {
    keymaps = function(tbl) --[[ custom keymap table parser function here ]] end,
    commands = function(tbl) --[[ custom command table parser function here ]] end, 
    autocmds = function(tbl) --[[ custom autocmd table parser function here ]] end,
    funcs = function(tbl) --[[ custom function table parser function here ]] end,
  },
})
```

The parsers must just return the raw properties used internally by each respective item type (e.g. keymaps must return `{ keys = string, implementation = LegendayModeMapping, description = string, opts = table }`).

The current legenday.nvim DSL would be provided as the default parser, and we could also offer a which-key.nvim parser.

Parsers could go under the `legendary.parsers` namespace so that there could even be 3rd party community made legendary parser plugins, simply by providing parsers under that module namespace and we could `require` them dynamically.

@olimorris thoughts/feedback/input?

**Comment by olimorris** [comment]
Is the thinking that people could port their existing mappings directly into `legendary` via a defined parser without any modification?

**Comment by mrjones2014** [comment]
Yup, like coming from `which-key.nvim` or other keymapping plugins like [nest.nvim](https://github.com/LionC/nest.nvim), which I used before starting the `legendary.nvim` project, it was a useful plugin but it was lacking some features and the project is abandoned now.

Additionally, the better separation of concerns would allow us to better unit test the parser layer and the data layer, allowing us then to incrementally improve the parser and allow for more DSL features (such as nesting, etc.).

To support features like nesting, we would need to implement the parser layer such that a parser may return a single or multiple items. For example, a possible parser for the following table would need to return a list of keymaps:

```lua
{
  -- nest keymaps under `<leader>` and they all get it as a prefix
  '<leader>',
  {
    'ff', -- keys effectively become `<leader>ff`
    ':Telescope find_files<CR>',
    description = 'Find files',
  },
  {
    'fb', -- keys effectively become `<leader>fb`
    ':Telescope buffers',
    description = 'Find buffers',
  },
}
```

**Comment by hinell** [comment]
But what's the use case? Purpose?

**Comment by mrjones2014** [comment]
closing as I haven't seen any demand for something like this.
