### ISSUE TITLE
Revamped documentation

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#28]
The README.md is getting quite big. We should break it down into either separate files or better organized sections.

We should have a section explaining in detail the required table structures for each type:

 - keymaps
 - commands
 - augroups
 - autocmds
 
And then a section on the Lua API functions, how/when to use them vs. using `require('legendary').setup()` etc.

**Comment by mrjones2014** [comment]
tagging @tsyroid for input :)

**Comment by tsyroid** [comment]
Agreed. Like the ideas above. Will be able to provide better feedback on how I see the groups/categories fall in a day or two.

**Comment by mrjones2014** [comment]
Reopening as the README.md could still use some work.

**Comment by tsyroid** [comment]
Under heading: Lua Helpers for Creating Mappings
> the Lua expressions are evaluated at the time they are bound
This is developer-speak. I'm just an everyday user. Translate please.
"the Lua expressions are evaluated when the mapping expression is called by the user"? or "at the time the mapping expression is first read by nvim"? or something else?

**Comment by mrjones2014** [comment]
It would be "the Lua expressions are evaluated at the time the mappings table is first read by nvim".

It has to evaluate in order to create/allocate the table.

Basically you need to give it the function _by value_ so that the function can be called at a later time (when you press the keys specified by the mapping).

**Comment by tsyroid** [comment]
And next paragraph down:

> If you need to call a function from a plugin, but do not want the require that the plugin be loaded at the time you define your keymaps (like if you're using Packer to lazy-load plugins), you can use...

If you need to call a function from Legendary [cap? or lower? it's not just _a_ plugin; its _this_ plugin] but don't require the plugin to be loaded when the keymaps are read (for example, if you're using Packer's lazy-loading feature), you can use...

TIP: If you want to tighten your technical (actually, any) writing up, here's one of the simplest tips I can give you. Any time you write anything, mentally scan (or physically search) for the word "that". Take it out. If the sentence still works, leave it out. If it doesn't leave it in. You will be amazed.

**Comment by tsyroid** [comment]
> It would be "the Lua expressions are evaluated at the time the mappings table is first read by nvim".
> 
> It has to evaluate in order to create/allocate the table.
> 
> Basically you need to give it _the function itself by reference_ so that the function can be called at a later time (when you press the keys specified by the mapping).

Good. Tell them (the reader) that.

**Comment by mrjones2014** [comment]
hey @tsyroid just wondering if you're working on a PR or if I should start making these changes.

**Comment by tsyroid** [comment]
Ooops. Sorry Mat. Mis-communication on my part.

I’ll do it — sometime today. Finally got the tools again.

Just back from some serious dumpster diving (and nvim restructuring).
