### ISSUE TITLE
[Feature]: Use item groups for Legendary built-ins

### ISSUE THREAD

**Issue by hinell** [mrjones2014/legendary.nvim#306]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I propose to group all Legendary entries by type:

```
keymaps
commands
functions
autocmds
```

I propose to expose above commands under `Legendary folder` in the legendary select menu. Thanks.

**Comment by mrjones2014** [comment]
Open to the idea as long as it’s behind an option. Submit a PR.
