### ISSUE TITLE
[Feature]: register existing commands with arguments

### ISSUE THREAD

**Issue by technicalpickles** [mrjones2014/legendary.nvim#309]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I'm trying to migrate from [command_center.nvim](https://github.com/FeiyouG/command_center.nvim) to legendary, and one thing I'm missing is I'm able to register commands w/ arguments:

```lua
			local command_center = require("command_center")
			command_center.add({
				{ desc = "Trouble: Toggle", cmd = "<CMD>Trouble<CR>" },
				{ desc = "Trouble: Document Diagnostics", cmd = "<CMD>Trouble document_diagnostics<CR>" },
				{ desc = "Trouble: Workspace Diagnostics", cmd = "<CMD>Trouble workspace_diagnostics<CR>" },
			})
```

In legendary, I can register an `Trouble` and not give it an implementation function:

```lua
	{
		'mrjones2014/legendary.nvim',
		-- sqlite is only needed if you want to use frecency sorting
		dependencies = {
			'kkharji/sqlite.lua',
			"folke/which-key.nvim",
		},
		event = "VeryLazy",
		opts = {

			commands = {
				{ ":Trouble", description = "Toggle Trouble", itemgroup = "Trouble"},
				{ ":Trouble document_diagnostics<CR>", description = "Trouble Document Diagnostics", itemgroup = "Trouble"},
				{ ":Trouble workspace_diagnostics<CR>", description = "Trouble Workspace Diagnostics", itemgroup = "Trouble" },
			},
			which_key = { auto_register = true },
		},
	}
```

It does show in results for `trouble`, but it doesn't include the subcommands:

![CleanShot 2023-02-09 at 08 41 57](https://user-images.githubusercontent.com/159/217828775-52cc57c5-82b1-4f0a-9e7d-8446d62ffdbb.png)

I'd guess that has to do with the 'command' having whitespace in it? I _think_ one way I can workaround this is to explicitly add keybindings for each of these?

**Comment by mrjones2014** [comment]
Hmm, interesting, I'd not thought of this use case. What you're running into is that fact that when actually _defining_ commands, the command must not have whitespace, since it's just a single command.

I see what you're trying to do, but the first item is meant more to be the actual command name.

Would it satisfy your use case to instead use keymaps or Lua functions? You could register it as a Lua function like so:

```lua
funcs = {
  { function() vim.cmd('Trouble')), description = 'Toggle Trouble', itemgroup = 'Trouble' },
  { function() vim.cmd('Trouble document_diagnostics')), description = 'Trouble Document Diagnostics', itemgroup = 'Trouble' },
  { function() vim.cmd('Trouble workspace_diagnostics')), description = 'Trouble Workspace Diagnostics', itemgroup = 'Trouble' },
}
```

**Comment by mrjones2014** [comment]
Also, looks like you aren't quite using item groups correctly. Item groups must be defined like so:

```lua
{
  itemgroup = 'Trouble',
  description = 'Trouble actions...',
  funcs = {
    { function() vim.cmd('Trouble')) end, description = 'Toggle Trouble' },
    { function() vim.cmd('Trouble document_diagnostics')) end, description = 'Trouble Document Diagnostics' },
    { function() vim.cmd('Trouble workspace_diagnostics')) end, description = 'Trouble Workspace Diagnostics' },
  }
}
```

**Comment by technicalpickles** [comment]
> Would it satisfy your use case to instead use keymaps or Lua functions? You could register it as a Lua function like so:

Yep, it definitely would!

> Also, looks like you aren't quite using item groups correctly.

Oh I see the problem now. I swear I saw that usage looking over the docs, but must of misread it.
