### ISSUE TITLE
[Feature]: use which-key's name as itemgroup

### ISSUE THREAD

**Issue by technicalpickles** [mrjones2014/legendary.nvim#310]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

When you register keys with [which-key.nvim](https://github.com/folke/which-key.nvim), you can add `name` which is displayed when you are in a group. For example, given this key:

```lua
			local keys = {
				x = {
					name = "Diagnostics",
					x = {"<CMD>TroubleToggle<CR>", "Toggle Trouble"},
					w = {"<CMD>Trouble workspace_diagnostics<CR>", "Workspace Diagnostics"},
					d = {"<CMD>Trouble document_diagnostics<CR>", "Document Diagnostics"},
					l = {"<CMD>Trouble loclist<CR>", "Location List"},
					q = {"<CMD>Trouble quickfix<CR>", "Quickfix"},
				}
			}
			local opts = {}

			wk.register(keys, opts)
			-- false if which-key.nvim handles binding them,
			-- set to true if you want legendary.nvim to handle binding
			-- the mappings; if not passed, true by default
			local handle_binding = false
			require('legendary.integrations.which-key').bind_whichkey( keys, opts, handle_binding)
```

![CleanShot 2023-02-09 at 09 24 45](https://user-images.githubusercontent.com/159/217839695-c35f5d86-9cc6-4883-895a-6dbb15786450.png)

I was hoping that this `name` would then show up in Legendary, but it doesn't:

![CleanShot 2023-02-09 at 09 25 18](https://user-images.githubusercontent.com/159/217839857-e1371452-b93f-49e2-b8bb-0ae8ff00a44c.png)

I've tried adding `itemgroup` in a few spots, and not seeing it have actually add the itemgroup. I'm looking at these lines:

https://github.com/mrjones2014/legendary.nvim/blob/3008ed68c8f309ced07587684c8af53884791d35/lua/legendary/integrations/which-key.lua#L43
https://github.com/mrjones2014/legendary.nvim/blob/3008ed68c8f309ced07587684c8af53884791d35/lua/legendary/integrations/which-key.lua#L22

And it _seems_ like adding it to the opts passed to `require('legendary.integrations.which-key').bind_whichkey` should end up in the items.

**Comment by mrjones2014** [comment]
This should definitely be do-able. I don't personally use which-key so it might take me a bit to figure out.
