### ISSUE TITLE
[Feature]: Do not hide grouped items

### ISSUE THREAD

**Issue by gregorias** [mrjones2014/legendary.nvim#322]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Could Legendary provide an option not to expose all elements under an item group in the global list? If I have a mapping like this:

```lua
{ ['<leader>'] = {
  f = { name='+Find',
    f = {..., 'Find file'}
    r = {..., 'Find register'}
  },
}},
```

Legendary should display both the item group "+Find" as well as individual "Find file" and "Find register" entires without me having to expand the "+Find" item group.

Legendary provides a neat function to group existing items and reuses Which Key's groups since https://github.com/mrjones2014/legendary.nvim/issues/310. Although grouping is a natural feature of Which Key's iterative workflow, it impairs Legendary workflow of providing an O(1) fuzzy-searchable list of commands. Grouping impairs the ability to find leaf entries.

**Comment by gregorias** [comment]
> What is the point of the group then in this case?

Discoverability. There are two kinds of queries Legendary would support with this:

1. When I know I want to find a file in my current directory, and I probably have a command for that, then I put in "findfilecurdir", and I'll get what I'm looking for.
2. Sometimes I don't know what commands I have at hand that could help me, so I want to remind myself "What were my Telescope commands that could be relevant for finding the file I need?" I would look for the "Telescope" group and dive in to browse.

**Comment by mrjones2014** [comment]
Couldn't you just not use a group and prefix the descriptions with `Telescope:` to get the same result? I ask because I'm not sure how we would currently do what you're asking without just duplicating the items, which is obviously not ideal and could also have performance implications. 

It seems a bit high risk/low reward to me.

**Comment by gregorias** [comment]
Yeah, that's acceptable to me. I started this mostly to surface the idea. Feel free to close this ticket.

**Comment by PetitBandit** [comment]
is there any way to disable in the config the group feature ?
I use groups within Whichkey but have no interest in using them with legendary that id rather want to use like a command palette fuzzy search which therefore should be able to search through every element including the commands inside groups.

**Comment by mrjones2014** [comment]
@PetitBandit there isn’t currently but if you open a new issue for that, it should be easy to have the which-key integration not create groups.

I’d happily take a PR, or if you just open a new issue, I’ll implement it when I get the time.
