### ISSUE TITLE
[Bug]: Legendary doesn't process which_key.mappings

### ISSUE THREAD

**Issue by gregorias** [mrjones2014/legendary.nvim#323]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Expected Behavior

Legendary displays mappings provided in `which_key.mappings`, i.e., the `Print foo` mapping provided in the minimal `init.lua`.

### Actual Behavior

Legendary does not display mappings provided in `which_key.mappings`, i.e., the `Print foo` mapping provided in the minimal `init.lua`.

### Minimal Configuration to Reproduce

```lua
-- | Fetches Lazy if not present.
local function bootstrap_lazy()
	local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
	if not vim.loop.fs_stat(lazypath) then
		vim.fn.system({
			"git",
			"clone",
			"--filter=blob:none",
			"https://github.com/folke/lazy.nvim.git",
			"--branch=stable",
			lazypath,
		})
	end
	vim.opt.rtp:prepend(lazypath)
end
bootstrap_lazy()

require("lazy").setup({
	{
		"mrjones2014/legendary.nvim",
		config = function()
			require("legendary").setup({
				which_key = {
					mappings = {
						["<space>f"] = {
							function()
								print("foo")
							end,
							"Print foo",
						},
					},
				},
			})
		end,
	},
})

```

### Output from :LegendaryLog

<details>
<summary><code>:LegendaryLog</code> output (click to expand)</summary>

```
[Thu Mar 23 21:47:17 2023][legendary.nvim] Took 0.478792 ms to filter items in context.
[Thu Mar 23 21:47:17 2023][legendary.nvim] Config.sort.frecency is enabled, but sqlite is not availabe, so frecency is automatically disabled.
[Thu Mar 23 21:47:17 2023][legendary.nvim] Launching select UI
```
</details>

### Additional Details and/or Screenshots

To reproduce:

1. Open Neovim with the provided init.lua.
2. Run `:Legendary`.

The error stems from incorrect length calculation in https://github.com/mrjones2014/legendary.nvim/blob/ee9e14955c9aa280e08b5600f7eb53e7c2578cd7/lua/legendary/init.lua#L90. The hash operator returns `0` for associative arrays that Which Key uses.

**Comment by mrjones2014** [comment]
Thanks for the detailed report and pointing out the bug! I don't personally use `which-key.nvim` so it's super helpful to have users help me catch stuff like this. I'll prepare a PR shortly.
