### ISSUE TITLE
Unexpected results from "first time" install

### ISSUE THREAD

**Issue by tsyroid** [mrjones2014/legendary.nvim#34]
Attempting to install/configure legendary to mimic the same behaviour I experienced running it under your nvim configuration (https://github.com/mrjones2014/dotfiles/tree/master/.config/nvim).

At the time I opened this issue (reference note: commit a62b717 in my current `nvim-dev` tree):
- it installs fine
- it loads fine (that is, I can access all the legendary commands from the command line and they work as advertised)
- I have no errors arising relating to legendary
- I have been through your README multiple times
- I have triple checked my config for all the obvious (it also loads and works without error or incident)
- My nvim install, overall, is behaving as it should -- no errors or issues

What I expect:
When I key-press <Ctrl-l> (in my install; was <Leader>l in your example) I should be a popup dialogue with a list of the maps and commands listed in my config file. Instead I get a list of all available nvim commands.
Screenshot attached.
Config file attached

<img width="832" alt="Screen Shot 2022-03-02 at 09 29 17" src="https://user-images.githubusercontent.com/867354/156419211-bb78fcf7-6e46-4c89-80ec-f391e6f97896.png">
[legendary.txt](https://github.com/mrjones2014/legendary.nvim/files/8171772/legendary.txt)
.

**Comment by tsyroid** [comment]
Clarification (I didn't get the format syntax right):
When I key-press `CTRL-l` (which, in your install is `LEADER-l`)

**Comment by mrjones2014** [comment]
>I should be a popup dialogue with a list of the maps and commands listed in my config file. Instead I get a list of all available nvim commands.

`legendary.nvim` includes built-ins, pass `include_builtin = false` to `setup()` to remove those.

As far as the way the screenshot looks, it appears you're just using the default `vim.ui.select()` handler. You can hook that up to a fuzzy finder with a plugin like dressing.nvim.

**Comment by tsyroid** [comment]
Mmm. I'm not sure I understand how the above addresses my issue.
I'm just trying to get my legendary install to look/act like yours. What do I need to do that?
Your config does not use `include_builtin`. (I did actually try it, and it makes to difference here to producing a popup window).
And _I'm_ not using anything (your reference to `vim.ui.select()` handler. Maybe your app is, but I wouldn't know. And again, I'm not trying to do anything 'fuzzy'. Remember, Mat, in the context of this issue, I'm just a user here. I installed your plugin. I want to make it look like 'the picture' (in this case, the picture in my head; or the gif you're displaying in the README). Tell me how :-) If you going to show a fancy screenshot, what you do in the text that follows has to somehow tell the reader how to produce something similar. It the law (in technical writing) ;-)

**Comment by mrjones2014** [comment]
Ah yeah I guess I need to be a little clearer on how I've got the UI setup.

`vim.ui.select()` is a generic Neovim API for providing a "select" interface. Internally, when you call `require('legendary').find()` it's pumping the items into `vim.ui.select()`.

In the recording I've got in the README.md, I'm using Telescope as my `vim.ui.select()` handler. I'm doing that via a plugin called `dressing.nvim` which takes care of setting up Telescope as the `vim.ui.select()` handler.

Maybe I should add a section about like a "recommended configuration" which includes installing and setting up `dressing.nvim`.

**Comment by mrjones2014** [comment]
`include_builtin` is to control whether or not you want built-in keymaps and commands to be registered with `legendary.nvim`.

**Comment by tsyroid** [comment]
Ah, OK. Now I have something to work with.

No. You don’t need to write/add anything. I’m going to do that for you.

What you need to do is show/guide me how to get my installation to look
like yours. Once I’m there, I’ll go to work on the README and ‘splain to
the others how to get there as well.

(Hi-hoh, Hi-hoh, it’s off to hack I go… )

**Comment by tsyroid** [comment]
Progress. One show-stopper left.

My keymap to open legendary doesn’t work (I reset it to control-p for
consistency with your install).

No idea. I don’t even know where to look, given (from what I gather) your
app somehow abstracts the vim.api.nvim_set_keymap function in order to hang
a ‘description’ field onto the UI. Don’t want to get buried in this, though
(another day, another issue).

Bottom line — No Bueno keymap. Where do I look for answer(s)?

Aside: This is a FUCKING COOL app, and I can see why you're stoked about
it. I still don’t have what I consider full functionality (ie, easy
access), but I can see how I could easily come to rely on this little gem
in my everyday workflow. So hang in there, and don’t let my critiques
distract you. Just keep doing what you’re doing — telling me about the
inner stuff. I’ll keep hammering until I understand, then I’ll translate
and abstract for Average-Joe-User.

/tom

**Comment by mrjones2014** [comment]
Can you link to where you’re mapping it? Only thing I can think of off the top of my head is, if it’s a string mapping, does it end in `<CR>`?

If I can see how it’s mapped though I’ll be able to help better.

> This is a FUCKING COOL app, and I can see why you're stoked about
it

Thanks! I’m finding it super useful, and creating new keymaps and commands is super quick and easy (once you have it set up and working, that is 😅)

**Comment by tsyroid** [comment]
>
> Can you link to where you’re mapping it?
>

Not sure what you mean by that. It shouldn't need a <CR> anywhere, cuz
we're triggering an action (require(‘legendary’).find) based on a
keystroke. But for some reason, legendary is not receiving that keystroke
(??). But all my other mappings are working OK. So it’s not something at
the level of the nvim_keymap api. It’s above.

Or. It could be something to do with the way my nvim configuration is
structured vis-a-vis your app. I’m not seeing any issues with any other
apps, but it’s possible we have an edge-case here somewhere. Pretty slim,
but I like to talk about elephants (in the room ;-)

/tom

Go back. Look at the config I attached to the issue. The only thing I’ve
changed is the keymap. My current config is using <CTRL-p> for consistency.

**Comment by mrjones2014** [comment]
So looking at your config, the way you have it set up, `legendary` would have to be loaded at the time that the `maps` table is first evaluated. If that's not the case in your setup, you can wrap it in a function like so:

```lua
local maps = {
  { '<C-l>', function() require('legendary').find() end, description = 'Search key bindings' },
}
```

**Comment by mrjones2014** [comment]
For example this could happen if you're lazy loading the plugin and the module containing `maps` is `require`d somewhere before `legendary` is loaded by the plugin manager. Not sure if you're doing lazy loading though.

**Comment by tsyroid** [comment]
I'm not (lazy loading; confirmed via `PackerStatus`)
And the above suggested change to my `local maps` entry produced this startup error: `legendary.lua:10: '=' expected near 'end'`

I resolved this whole "one showstopper left" issue by simply adding a legendary mapping to my `user/remaps.lua` file (`map('n', '<c-l>', ':Legendary<CR>')`). This doesn't really 'splain' why your supplied configuration didn't work for me, other than to say it's a nuance of my nvim-config setup. Which I'll address when I rework your README (see below).

I think we can call this issue closed. But I'll let you push the button if you feel the same.

To recap:

* Your README is definitely missing some important bits, which I'll circle back on and address in another open issue.
* Most important (to the above) is `dressing.nvim` (and the inherent explanation you gave of how your app works); once I added this to my nvim-config, it immediately allowed me to move forward and fill in a bunch of other holes I see need explaining in your README (which, again, I'll address in an open issue)
* There are other suggestions/improvement ideas this thread has invoked, but they belong in new issues.
* I'm going to write the "showstopper" keymap issue off to a quirk of my install. Which I will also address somehow in my re-write of your README.

Cheer, and kudos Mat.

**Comment by mrjones2014** [comment]
>Most important (to the above) is `dressing.nvim`

I added a [little bit about it under Prerequisites](https://github.com/mrjones2014/legendary.nvim#prerequisites) but it could definitely still be improved. Looking forward to seeing your suggestions.
