### ISSUE TITLE
[Bug]: Doesn't display full output of CmpStatus

### ISSUE THREAD

**Issue by gregorias** [mrjones2014/legendary.nvim#345]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.8.3

### Expected Behavior

Selecting `CmpStatus` in Legendary runs the command and displays the full status:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/722385/230481934-d942755e-efb8-4603-8537-b34e5d1d432d.png">

I.e., the expected behavior is the same as running the command directly from the command line (`:CmpStatus`).

### Actual Behavior

(Use the minimal config provided)

1. Open a file with Neovim, e.g., `nvim .config/nvim/init.lua`.
2. Open Legendary `:Legendary`
3. Select `CmpStatus` and press Enter.

You'll now need to press enter 3-4 times to get the full output of CmpStatus.

### Minimal Configuration to Reproduce

```lua
-- | Fetches Lazy if not present.
local function bootstrap_lazy()
	local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
	if not vim.loop.fs_stat(lazypath) then
		vim.fn.system({
			"git",
			"clone",
			"--filter=blob:none",
			"https://github.com/folke/lazy.nvim.git",
			"--branch=stable",
			lazypath,
		})
	end
	vim.opt.rtp:prepend(lazypath)
end
bootstrap_lazy()

require("lazy").setup({
	{ "stevearc/dressing.nvim" },
	{
		"mrjones2014/legendary.nvim",
		config = function()
			require("legendary") l.setup({ commands = { { "CmpStatus", description = "Show Cmp's statuses." } } })
		end,
	},
	{
		"hrsh7th/nvim-cmp",
		dependencies = { "hrsh7th/cmp-buffer" },
		config = function()
			local cmp = require("cmp")
			cmp.setup({ sources = cmp.config.sources({ { name = "buffer" } }) })
		end,
	},
})
```

### Output from :LegendaryLog

<details>
<summary><code>:LegendaryLog</code> output (click to expand)</summary>

```
-- | Fetches Lazy if not present.
local function bootstrap_lazy()
	local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
	if not vim.loop.fs_stat(lazypath) then
		vim.fn.system({
			"git",
			"clone",
			"--filter=blob:none",
			"https://github.com/folke/lazy.nvim.git",
			"--branch=stable",
			lazypath,
		})
	end
	vim.opt.rtp:prepend(lazypath)
end
bootstrap_lazy()

require("lazy").setup({
	{ "stevearc/dressing.nvim" },
	{
		"mrjones2014/legendary.nvim",
		config = function()
			require("legendary") l.setup({ commands = { { "CmpStatus", description = "Show Cmp's statuses." } } })
		end,
	},
	{
		"hrsh7th/nvim-cmp",
		dependencies = { "hrsh7th/cmp-buffer" },
		config = function()
			local cmp = require("cmp")
			cmp.setup({ sources = cmp.config.sources({ { name = "buffer" } }) })
		end,
	},
})
```
</details>

### Additional Details and/or Screenshots

If I just run `vim.api.nvim_cmd({cmd = 'CmpStatus'}, {})`, everything works as expected. How does Legendary execute commands?

**Comment by mrjones2014** [comment]
I ran the following line: `:lua vim.keymap.set('n', '<leader>c', function() vim.api.nvim_cmd({ cmd = 'CmpStatus' }, {}) end)` and then with that `<leader>c` produces the same behavior, so I'm not sure it actually directly has anything to do with legendary itself.

With your command definition, `legendary.nvim` would be using `vim.cmd` to execute it. https://github.com/mrjones2014/legendary.nvim/blob/0d42c70bddb447b75a3bd9b0c26d826dc809b8e0/lua/legendary/api/executor.lua#L53-L90

I'm not sure what's causing this exactly, but I don't think it's directly `legendary.nvim`.

**Comment by gregorias** [comment]
Thank you, I've reported it to nvim-cmp instead, https://github.com/hrsh7th/nvim-cmp/issues/1512.
