### ISSUE TITLE
[FEATURE]: Allow starting the finder from a custom root item group

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#390]
### Discussed in https://github.com/mrjones2014/legendary.nvim/discussions/389

<div type='discussions-op-text'>

<sup>Originally posted by **towry** July  6, 2023</sup>
I want to use legendary as folder action select, so I can select folder from telescope and use legendary.

So I write the script as following:

```lua
return function (cwd)
  legendary.funcs({
    itemgroup = 'Folder action',
    funcs = {},
})

legendary.find({
  select_prompt = 'Folder action under: ' .. cwd,
  filters = {
   --- how to write this??
  }
})
end
```

how to write the filters so that only everything under 'Folder action' item group shown?

I have looked over the docs, nothing found.</div>

**Comment by mrjones2014** [comment]
I'll need to think about how to implement this exactly. When you add keymaps to legendary, there is a parse step, so that means that when you would pass items to the finder as a custom "root" we would need to figure out:

- is this a list of unparsed item tables?
- Is this a list of parsed legendary items?
- something else?

@towry how would you feel about the API just accepting a group name as a string, and then legendary would look up the group by name?

So, you could do something like:

```lua
require('legendary').find({ itemgroup = 'My item group' })
```

**Comment by towry** [comment]
Yes, I have randomly tried this API, I think it is intuitive.

**Comment by mrjones2014** [comment]
@towry can you give #391  a test for me? 🙏

**Comment by towry** [comment]
@mrjones2014 It works.
![截屏2023-07-07 08 46 32](https://github.com/mrjones2014/legendary.nvim/assets/8279858/8d8ad87d-538a-4aea-aebd-dd0e801fd301)
![截屏2023-07-07 08 46 57](https://github.com/mrjones2014/legendary.nvim/assets/8279858/7486d67f-57e4-4935-8f15-9a94f70ba3a6)

**Comment by towry** [comment]
My current usage is a bit tedious because I have to manage many temporary variables. I am not sure if I am overusing the legendary functions API, but it seems to work well with various plugins as popup menus (or context menus). Otherwise, I would have to use other plugins to meet my needs, which would greatly improve my workflow in a monorepo codebase.

Thanks for the work, much appreciate.

```lua
local M = {}

local cwd = nil
local legendary_registered = false
local item_group_name = 'folder_actions'

function M.enter(new_cwd)
  cwd = new_cwd
  return M
end

local get_current_cwd = function() return cwd end

function M.then_folder_action()
  local lg = require('legendary')
  local select_prompt = 'Folder action under: ' .. require('userlib.runtime.path').home_to_tilde(cwd)

  if not cwd then return end

  if legendary_registered then
    lg.find({
      select_prompt = select_prompt,
      itemgroup = item_group_name,
    })
    return
  end
  legendary_registered = true

  lg.funcs({
    itemgroup = 'folder_actions',
    description = 'Folder actions',
    funcs = {
      {
        description = 'Open with mini.files',
        function()
        end,
      },
      {
        description = 'Open with NVimTree',
        function()
        end,
      },
      {
        description = 'Find files with telescope',
        function()
          require('userlib.telescope.pickers').project_files({
            cwd = get_current_cwd(),
            use_all_files = true,
          })
        end,
      },
      {
        description = 'Recent files',
        function()
          require('userlib.telescope.pickers').project_files({
            oldfiles = true,
            cwd_only = true,
            cwd = get_current_cwd(),
          })
        end,
      },
      {
        description = 'Search content',
        function()
          require('userlib.telescope.live_grep_call')({
            cwd = get_current_cwd(),
          })
        end,
      },
    }
  })

  lg.find({
    select_prompt = select_prompt,
    itemgroup = item_group_name,
  })
end

return M
```

**Comment by mrjones2014** [comment]
Instead of 

```lua
function M.enter(new_cwd)
  cwd = new_cwd
  return M
end

local get_current_cwd = function() return cwd end
```

You can just use `vim.cmd.cd(new_cwd)` and `vim.loop.cwd()`. To replace `$HOME` with `~` you can just use `vim.fn.fnamemodify(path, ':~:.')`.

As far as keeping track of `legendary_registered`, why don't you just register them via `require('legendary').setup()` wherever you set up the plugin? It doesn't look like they are actually dependent on the `cwd`. There is also `autocmd DirChanged` and `autocmd DirChangedPre` if that helps.
