### ISSUE TITLE
[Feature]: config option to allow entries merge of [keymaps, commands] with [functions]?

### ISSUE THREAD

**Issue by MikeLemo1** [mrjones2014/legendary.nvim#443]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

A simple boolean binary option that allows merging of Legen functions to keymaps and commands list search,
wil probably come handy in the future.

**Comment by mrjones2014** [comment]
I'm not sure what you mean. Everything is searched together by default.

**Comment by MikeLemo1** [comment]
Yes just noticed that this arised from suspecting that functions are searched separately after configuring it wrong and maybe the docs were written like functions are a bit separated from the commands and keymaps in the philosophy.
Anyways yeah 
nvm all as expected nothing wrong.
