### ISSUE TITLE
Integration with Which-Key

### ISSUE THREAD

**Issue by bennypowers** [mrjones2014/legendary.nvim#7]
Plugin looks great! Would love it if I could plug in my which_key tables to the fuzzy finder here - a real replacement for atom command palette. Which key and legendary could really complement each other perfectly

It's two different tasks: "I remember the leader key category but can't remember what's under it" (which key) vs "I remember the description but not the command or binding" (legendary)

In Atom, there's the command palette for the latter and the keybinding resolver for the former

Longer term, we can imagine a pseudo-standard way to document and describe bindings and commands that any UI could consume and display

**Comment by mrjones2014** [comment]
I would absolutely love to work with @folke (author of which-key.nvim) on this if you'd be generous enough to work with me on it!

I'm not sure if it's a better approach to try to parse which-key style tables into the style I currently use, or to refactor my code to natively support which-key style bindings.

One consideration we'd have to make is that my plugin can not only remember your key binds and commands but also _define/create_ them. I don't think which-key style tables supports having the implementation of the keymap/command in the table itself.

**Comment by bennypowers** [comment]
A third option would be for both plugins to agree on a shred data structure and access API which other plugins could make use of as well. then each plugin would be responsible for, along the way, translating their own config tables into that shared table.

**Comment by mrjones2014** [comment]
That's a neat idea but I'm not sure what that would look like. At the most basic level, maybe something basically like mine but instead of them being based on index, each one would need an explicit key. So where mine look like:

```lua
{ '<F3>', ':NvimTreeToggle<CR>', description = 'Toggle file tree' }
```

perhaps a standardized version could look like:

```lua
{ key =  '<F3>', impl = ':NvimTreeToggle<CR>', description = 'Toggle file tree' }
```

**Comment by mrjones2014** [comment]
>maybe that could be internally keyed by something like ${description}__NVIM_BINDING_RECORD__${key}

not sure what you mean by that?

**Comment by bennypowers** [comment]
say there were two commands called "Format Buffer" but one was `<c-f>` and one was `<leader>lf`

If we keyed it by "Format Buffer", one would be clobbered

so we'd need to key two bindings:

`Format Buffer__NVIM_BINDING_RECORD__<c-f>` and `Format Buffer__NVIM_BINDING_RECORD__<leader>lf`

not sure how much sense that actually makes 😅

**Comment by mrjones2014** [comment]
>Format Buffer__NVIM_BINDING_RECORD__<c-f> and Format Buffer__NVIM_BINDING_RECORD__<leader>lf

why is this needed at all?

**Comment by bennypowers** [comment]
i'm assuming the bindings are stored in a json-object like structure

but you're right, if they're stored in a list, this isn't an issue

**Comment by mrjones2014** [comment]
I looked a little more at which-keys table format and I think I can implement some kind of parser and have which-key tables "just work" with my plugin. they're similar but slightly different formats.

example:

which-key table representing "press `ff` to find files with telescope" (from their README.md):

```lua
{
  f = {
    name = "file", -- optional group name
    f = { "<cmd>Telescope find_files<cr>", "Find File" }
}
```

would need to be converted to the legendary table:

```lua
{ 'ff', '<cmd>Telescope find_files<cr>', description = 'Find File' }
```

Once I find the "last level" of nesting, it's basically a matter of combining the upwards key path into a string (e.g. `{ f = { f = { something } } }` => key = 'ff'), using the indexed first element (`tbl[1]`) as the implementation (so, the 2nd element of my table), and the indexed 2nd element (`tbl[2]`) as the `description` field of my table.

Of course we'd also copy the things like `noremap = false, buffer = 123` from the which-key table into the `opts` sub-table of my table.

**Comment by mrjones2014** [comment]
@folke are there any edge cases surrounding this or is what's in the README.md pretty much the extent of how you can define which-key tables?

**Comment by mrjones2014** [comment]
New discovery -- we can have which-key do the parsing for us!

If I take the mappings from the readme [here](https://github.com/folke/which-key.nvim#%EF%B8%8F-mappings) and pass them into `require('which-key.keys').parse_mappings` like so:

```lua
require('which-key.keys').parse_mappings({}, {
  f = {
    name = 'file',
    f = { '<cmd>Telescope find_files<cr>', 'Find File' },
    r = { '<cmd>Telescope oldfiles<cr>', 'Open Recent File', noremap = false, buffer = 123 },
    n = { 'New File' },
    e = 'Edit File',
    ['1'] = 'which_key_ignore',
    b = {
      function()
        print('bar')
      end,
      'Foobar',
    },
  },
}, '<leader>')
```

I get the following result:

```lua
{
  {
    buf = 123,
    cmd = '<cmd>Telescope oldfiles<cr>',
    label = 'Open Recent File',
    opts = {
      noremap = false,
    },
    prefix = '<leader>fr',
  },
  {
    label = 'New File',
    opts = {},
    prefix = '<leader>fn',
  },
  {
    cmd = '<cmd>Telescope find_files<cr>',
    label = 'Find File',
    opts = {},
    prefix = '<leader>ff',
  },
  {
    label = 'Edit File',
    prefix = '<leader>fe',
  },
  {
    cmd = '<cmd>lua require("which-key").execute(3)<cr>',
    label = 'Foobar',
    opts = {},
    prefix = '<leader>fb',
  },
  {
    label = 'which_key_ignore',
    prefix = '<leader>f1',
  },
  {
    group = true,
    label = 'file',
    prefix = '<leader>f',
  },
  {
    group = true,
    prefix = '<leader>',
  },
}
```

which should be pretty trivial to then convert and parse in my plugin.

**Comment by mrjones2014** [comment]
not sure how we'd handle the `prefix` thing though as that option is in a separate table.

**Comment by mrjones2014** [comment]
@bennypowers I think I've got a pretty good which-key integration implemented! I tested it with your which-key config from your dotfiles repo, and it seems to work well. See updated README.md for instructions! Please file another issue if you run into problems!
