### ISSUE TITLE
Don't require `which-key` to be loaded at the time of legendary `setup()` call to set up `which-key` listener

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#78]
Currently calling `require('legendary').setup()` will only set up the `which-key` listener if `which-key` is available/loaded on the runtimepath.

I think there are ways around this, e.g. Packer has a lazy-load option to lazy load based on the require path.

**Comment by mrjones2014** [comment]
it's a super hack but maybe something like:

```lua
local original_require = require
require = function(path)
  if vim.startswith(path or '', 'which-key') then
    // try to setup the listener
  end
  return original_require(path)
end
```

**Comment by mrjones2014** [comment]
I don't think that'll work because `require` is read-only. How the heck does `packer` handle it then? it has an option to lazy load lua modules based on require path.

**Comment by mrjones2014** [comment]
Perhaps we can ask the which-key author to add an `autocmd User WhichKeyLoaded` that gets fired as soon as the plugin becomes available on the runtimepath.

**Comment by mrjones2014** [comment]
maybe this is the answer: https://www.lua.org/manual/5.4/manual.html#pdf-package.searchers

**Comment by rafamadriz** [comment]
In case which-key adds support for the `desc` option when creating a new mapping. Wouldn't that make the integration much easier ? I believe you wouldn't need any specific code for which-key in your plugin.

For reference:
folke/which-key.nvim#253 
folke/which-key.nvim#242

**Comment by mrjones2014** [comment]
@rafamadriz I think you’re misunderstanding the intent of this issue.

My goal here is basically to make the integration easier to use.

Currently, the integration requires that `which-key.nvim` be available on the runtime path, but to call `require(‘legendary’).setup()` before calling `require(‘which-key’).register(wk_tbls, wk_opts)`.

When you call `require(‘legendary’).setup()` it attempts to add a listener for when you call `require(‘which-key’).register(wk_tbls, wk_opts)`. However, if `which-key.nvim` isn’t loaded yet (e.g. the `require` call fails), then the integration just doesn’t work.

What I’d like to figure out how to do is automatically detect when `which-key.nvim` becomes available on the runtime path and load the listener for the integration at that time.

**Comment by mrjones2014** [comment]
Figured out how to do this with `package.searchers`!
