### ISSUE TITLE
Commands should have a `<CR>` appended if there isn't one

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#79]
In #77  we changed the executor to always use `nvim_feedkeys`. This had the unintended side effect of commands just filling the command line and not running if they don't end in `<CR>`.

We need to append one if it's missing.

**Comment by mrjones2014** [comment]
@olimorris I'm pretty confident in this commit but please let me know if I broke your keymap from yesterday 😅

**Comment by olimorris** [comment]
Seems all great to me!
