### ISSUE TITLE
Integration with 'personal' keymaps

### ISSUE THREAD

**Issue by tsyroid** [mrjones2014/legendary.nvim#82]
Meaning, my efforts at integrating `legendary` with my `mappings-ng.lua` file.

I've achieved this by using the `:require('legendary').bind_whichkey(wk_tbls, wk_opts)` (thanks to mat) command from the vim comandline. All good. But when I tried to integrate this into my config (by using the above 'require' in place of my 'require('legendary').setup()' line everything blew up (nvim init failed).

My current (working) config is attached for reference.

Seems to me this solution is rather 'inelegant'. Looking for a cleaner solution.

/tom

[paste.md](https://github.com/mrjones2014/legendary.nvim/files/8308316/paste.md)

**Comment by mrjones2014** [comment]
pasting the snippet for convenience:

```lua
-- nvim/lua/configure/legendary.lua

local path

local paths = require('paths')
if vim.fn.isdirectory(paths.join(paths.home, 'Projects/legendary.nvim')) > 0 then
  path = '~/Projects/legendary.nvim'
else
  path = 'mrjones2014/legendary.nvim'
end

return {
  path,
  config = function()
    require('legendary').setup()
    require('legendary').bind_whichkey(TS.leader_nmap, TS.leader_xmap)
  end,
}
```

**Comment by mrjones2014** [comment]
Seems like we can't reproduce this issue. Regardless, I've updated setup so that you can make the config a little cleaner:

https://github.com/mrjones2014/legendary.nvim/commit/74229ea6b56fcc8df5b2be2e4af56ab5b54575d0
