### ISSUE TITLE
Sort by mapping/command

### ISSUE THREAD

**Issue by cseickel** [mrjones2014/legendary.nvim#9]
It would be nice to have a way to sort the list. Is the sort controlled by Legendary or the configured select function? I'm using Telescope via dressing right now.

**Comment by mrjones2014** [comment]
I need to verify but I'm pretty sure sorting will be controlled via Telescope. I can test sorting before I give the items to `vim.ui.select()` and see if that does anything.

**Comment by mrjones2014** [comment]
I looked into this a bit and it looks like it will be up to the implementer of `vim.ui.select()` to decide on and implement the sorting.

See example in `dressing.nvim`: https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/select/telescope.lua#L33

I recommend opening an issue there for `dressing.nvim` to support customizing the sorting.

I also plan on implementing #10 which may help your use case a little.

**Comment by cseickel** [comment]
Thanks for looking into this. 

The problem for me, which I bet you will hear more of as more people find this plugin, is that the options I want to set on the `vim.ui.select()` implementer are very specific to this source. I'm sure this concept will apply to more than just sorting. You may want to think about creating your own implementation just so that it can be configured, or creating a telescope extension for Legendary that can expose options for sorting, size, etc.

**Comment by mrjones2014** [comment]
As of right now I don't think there is a way to pass extra configuration through `vim.ui.select()` in the way you're describing.

>You may want to think about creating your own implementation just so that it can be configured, or creating a telescope extension for Legendary that can expose options for sorting, size, etc.

These things would both sorta defeat the purpose of using `vim.ui.select()` which is so that it can be hooked up to any select implementation you want.

**Comment by mrjones2014** [comment]
I'm happy to review a PR if you have something specific in mind though.

**Comment by cseickel** [comment]
There does seem to be the ability to at least specify what is be displayed in the select api. If Legendary sets the `kind` field in the opts to something like 'legendary', then I think we can use the `get_config` option in dressing to pass the desired options on to the final presentation layer. There still may be some work downstream, but it start with Legendary setting that `kind` option.

I might submit a PR at some point, but I am a little busy with neo-tree ATM. I gotta fix that pesky "close if last window" bug after all. :wink:

**Comment by mrjones2014** [comment]
@cseickel I can definitely set the `kind` option if that will make it easier for you to sort!

> I gotta fix that pesky "close if last window" bug after all. 😉

LOL didn’t even realize you were the same person I was chatting with on that issue till now 😂
