### ISSUE TITLE
[Bug]: Description column in UI is misaligned if keymap contains specialchar

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/legendary.nvim#96]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```bash
NVIM v0.7.0-dev+nightly
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/Oli/.neovim/1647624272/build/config -I/Users/Oli/.neovim/1647624272/src -I/Users/Oli/.neovim/1647624272/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/Users/Oli/.neovim/1647624272/build/src/nvim/auto -I/Users/Oli/.neovim/1647624272/build/include
Compiled by Oli@Oli

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

### Expected Behavior

The three columns in the `legendary` UI should always be aligned

### Actual Behavior

The special chars I have in four of my keymaps cause a weird misalignment in the columns:

<img width="1134" alt="Screen Shot 2022-03-21 at 07 57 00@2x" src="https://user-images.githubusercontent.com/9512444/159222547-cf02022a-36db-4549-b327-999dc1a84549.png">

### Minimal Configuration to Reproduce

```lua
local maps = {
  { "∆", "<cmd>move+<CR>==", description = "Move line down" },
  { "˚", "<cmd>move-2<CR>==", description = "Move line up" },
  { "∆", ":move'>+<CR>='[gv", description = "Move line down", mode = { "v" } },
  { "˚", ":move-2<CR>='[gv", description = "Move line up", mode = { "v" } },
}
require("legendary").bind_keymaps(maps)
```

**Comment by mrjones2014** [comment]
Interesting. Why do you need to use the special characters? For me, the triangle character ∆ for example is output from pressing `<A-j>`.

I should still fix this regardless. Not sure exactly what causes it though. I think it may have something to do with the number of bytes ∆ takes up or something.

**Comment by mrjones2014** [comment]
Solution found here for computing the utf-8 length of strings: http://lua-users.org/wiki/LuaUnicode

Got a workable solution here but I'd like to do some performance testing because it involves iterating over the string characters in Lua.

Probably won't be too much of a problem because LuaJIT is pretty fast but I want to make sure.

**Comment by olimorris** [comment]
> Interesting. Why do you need to use the special characters? For me, the triangle character ∆ for example is output from pressing `<A-j>`.
> 
> I should still fix this regardless. Not sure exactly what causes it though. I think it may have something to do with the number of bytes ∆ takes up or something.

I can't get the damn `alt+key` to work on MacOS and Kitty...at all! So have to resort to those special chars.

Let me add, this is so low priority, just thought I'd flag in case anyone has it. I see a view dotfiles which use the special chars so in case they ever pickup `legendary`.

**Comment by mrjones2014** [comment]
>I can't get the damn alt+key to work on MacOS and Kitty...at all! So have to resort to those special chars.

Do you have `macos_option_as_alt both` set in `kitty.conf`?

**Comment by mrjones2014** [comment]
@olimorris the padding issue should be fixed now, reopen if not.

**Comment by olimorris** [comment]
Beautiful. Thanks

**Comment by mrjones2014** [comment]
> And yep I do!

Interesting. I didn't have to do anything beyond setting that Kitty option and my alt/option key works totally normally. 🤔
