### ISSUE TITLE
[Feature]: Option to lazy-load key maps with an autocmd 

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/legendary.nvim#99]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

I’m imaging an API like defining the keymap like so:

```lua
{
  ‘<leader>p’,
  require(‘legendary.helpers’).lazy(some_func, some_arg),
  description = “something”,
  opts = {
    lazy = {
      event = { ‘FileType’ },
      pattern = { “rust” }
    }
  }
}
```

The above keymap definition would only be created when you enter a Rust file.

**Comment by mrjones2014** [comment]
The more I thought about this the more I think it's kinda dumb and adding unnecessary complexity because you could just create a normal autocmd through legendary and then use the API to define new keymaps in the autocmd callback function...

**Comment by tversteeg** [comment]
Wouldn't this still be a nice feature for simplicity of configuration's sake? I like that I can now have all my key bindings in a neat single list without forcefully having to group them by lazy loading type in autocmd callback functions.

**Comment by mrjones2014** [comment]
>Wouldn't this still be a nice feature for simplicity of configuration's sake?

Yes, but it adds a lot of internal complexity. It's not as simple as "just create the autocommands". The API functions to do so need to be deterministic and, more importantly, idempotent.

What happens if the API functions get called again? Do we create a 2nd autocommand? Do we not? I think different users will have different answers. This is part of the reason I decided to leave it up to the users to implement this behavior with their own autocommands.

I would be open to entertaining a review and discussion of a well-written PR implementing the feature. I can't guarantee it will be accepted.
